# Generated by Django 3.0.7 on 2020-07-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='shoppingdetails',
            name='pid',
            field=models.CharField(max_length=100),
        ),
    ]
